name: Daily News Archive

on:
  schedule:
    - cron: '0 0 * * *'  # UTC时间每天0点（北京时间8点）
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run Archiver
        run: |
          python src/daily_news_archiver.py
          echo "=== 文件验证 ==="
          find archive/ -type f -ls

      - name: Direct Push
        run: |
          git config --global user.name "Haoqi7"
          git config --global user.email "w00989988@gmail.com"
          git add -A
          git commit -m "Auto-archive: $(date +'%Y-%m-%d %H:%M')" || echo "无新内容"
          git push origin main
