name: Daily NewArchive

on:
  schedule:
    - cron: '0 0 * * *'  # UTC时间每天0点（北京时间8点）
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Create archive directory
        run: |
          mkdir -p archive
          chmod -R 777 archive

      - name: Run Archiver
        run: |
          set -e  # 遇到错误立即退出
          python src/daily_news_archiver.py
          echo "=== 文件生成验证 ==="
          ls -R archive/

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
